### ISSUE TITLE
Could not connect to MariaDB in container from outside

### ISSUE THREAD

**Issue by jroew** [JSurf/docker-rpi-mariadb#6]
As of today (22. July 2020) I could not connect to the MariaDB instance from outside of the container. Yesterday it was working fine.
After fiddling around for hours I found the binding address in /etc/mysql/mariadb.conf.d/50-server.cnf was set to 127.0.0.1 instead of 0.0.0.0. I added a volume for it and changed it accordingly, which fixed the issue.

You might consider changing the binding address to 0.0.0.0 by default in the configs, as the container is usually accessed from outside, not localhost.

Cheers

**Comment by RRFfm** [comment]
Hi jroew, thanks for that info! after creating a new volume with changed binding address my nextcloud installation worked again

**Comment by nesasio93** [comment]
@jroew thank you very much! I had the same problem as @RRFfm and had no idea why my nextcloud wasn't working 👍

**Comment by JSurf** [comment]
Switched the base image from raspbian jessie to buster. This might have caused the issue. Sorry for that. Unfortunately i don't have much time to fix this in the  next 2 weeks, so please be patient and use the described workaround

**Comment by JSurf** [comment]
Please try the latest build from today if it manages to gets built. Found the necessary change in the official Dockerfile of mariadb
